### ISSUE TITLE
Invalid scope errors from prod OAuth2 service

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#1020]
I know we're not supposed to use this for production issues, but I emailed the SDS Team three hours ago and have had nothing back yet.  I'll close it later today.

We get an invalid scope error when trying to get an auth token for read:vat and write:vat scopes.  We've made no changes on our side; it just started happening this morning.  We can get a token for each of those scopes individually, however we can't then call any endpoints with it.

This is affecting all users of the bridging software (including me!) so I was just wondering if any other MTD software providers are seeing the same thing?  Or if anyone from the dev team has heard of the issue today.

**Comment by JeeBeePee** [comment]
Worked it out... we were URL encoding a + as a separator between the scopes. That has worked for 5 years, but no more. Changed to a space, working now. Will close this.

**Comment by wapenshaw** [comment]
> This is affecting all users of the bridging software (including me!) so I was just wondering if any other MTD software providers are seeing the same thing? Or if anyone from the dev team has heard of the issue today.

@JeeBeePee We were facing the same issue since 4-5 days. Just removing the + from the scope fixed it. Thank you for posting this here saved us a lot of headache debugging 

I was wondering if this breaking change was ever communicated officially? I checked all my emails but nothing about this and was wondering if there is some place else we need to monitor for changes like this. Even the releases section change logs dont mention this.

**Comment by JeeBeePee** [comment]
@wapenshaw There was no communication, and SDS Team was completely unaware of it. It does actually meet the spec at https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints now.
