### ISSUE TITLE
Liabilities API "type" field

### ISSUE THREAD

**Issue by nigelrainer** [hmrc/vat-api#116]
SDS have not been able to help on this issue, so have advised me to post here.

We are testing the liabilities API and have received back the following response in the Sandbox:

{"liabilities":[
{"taxPeriod":{"from":"2017-01-01","to":"2017-04-05"},"type":"PAYE","originalAmount":463872,"outstandingAmount":463872,"due":"2017-05-12"},{"taxPeriod":{"from":"2017-04-01","to":"2017-04-30"},"type":"VAT Return Debit Charge","originalAmount":15,"outstandingAmount":15,"due":"2017-06-09"},{"taxPeriod":{"from":"2017-08-01","to":"2017-08-31"},"type":"VAT CA Charge","originalAmount":8493.38,"outstandingAmount":7493.38,"due":"2017-10-07"},{"taxPeriod":{"from":"2017-10-01","to":"2017-12-01"},"type":"VAT OA Debit Charge","originalAmount":3000,"outstandingAmount":2845,"due":"2017-12-31"}]}

We are not interested in liabilities that relate to things like “PAYE” and want to filter for those relating to VAT.  My questions are:

1. Is there documentation on the available settings HMRC will use for the “type” field and what they mean?  For example, what are the differences between the different types of VAT charges above and what other settings might we expect to get back that aren’t in the sample response?
2. It would be useful in the API call to specify that we only want details of VAT liabilities.  Is this intended to be available at some point?

**Comment by MarkAKelly** [comment]
Hi @nigelrainer,

To answer your first question you would need to contact a tax expert or accountant, for advice on the different penalties and surcharges that HMRC may apply to a VAT account.

In answer to your second question: You will be provided with the liabilities for the regime you request against. If you use the MTD VAT Service `/vat/{vrn}/liabilities` to retrieve liabilities then only liabilities pertaining to that 'vrn' 's VAT account will be returned. 

We informed SDST that there had been an issue with the canned test data and believed that this was the root cause of your concern from 27 March.  Hope this helps.

Mark

**Comment by nigelrainer** [comment]
Thank you for your answer on the second point.

I find your first answer unhelpful.  Firstly, I am a tax professional (CIOT qualified with 28 years experience, 20 years in the tax technology space).  I want to know what type codes you intend to use and what they mean, so we can interpret them correctly in our software - a simple enough question.  This is a software issue and not one of tax - so again, what type codes can we expect, what do they mean and where is the documentation to support what you are putting in the API?  This later point is a much wider issue than just this "type" code - documentation provided by HMRC to date is, in my opinion, woeful.

**Comment by MarkAKelly** [comment]
Hi @nigelrainer,

Apologies if you found the answer unhelpful.  I would suggest, as ever with business or VAT specific queries, to go through SDSTeam@hmrc.gsi.gov.uk and your question can be directed down the appropriate route.  It unfortunately appears on this occasion that your specific question around the types of VAT charge has been passed on with the rest of your query through the wrong channel.

On this occasion I've passed this along to those responsible for maintaining the VAT vendor guide so that the appropriate information can be disseminated.  I have also suggested a review to look at whether this teams API documentation is an appropriate place for this information.

We will try and answer queries to the best of our knowledge, but please remember this a channel for technical issues that relate directly to technical issues developing against this service, and as such all queries are directed at developers. 

I will follow this up again tomorrow to make sure that you receive the information you need.

Many thanks,
Mark
