### ISSUE TITLE
HMRC Sandbox version - multiple VAT submissions for a Customer

### ISSUE THREAD

**Issue by liam-lagay-14** [hmrc/vat-api#183]
Hi,

I've been able to successfully communicate with the HMRC Sandbox with regards to submitting a VAT Return in a given quarterly period (April - June 2018 in my case). 

However, I don't seem to be able to then submit a VAT Return for the next period (in this case, July - September 2018), as the obligation period returned still states April - June 2018 (this period has not been marked as Fulfilled in this the obligation task output we received back). 

One of my colleagues has indicated that this is a potential HMRC Sandbox limitation. Is this the case and if so, are there any plans to extend the API to handle multiple consecutive submissions going forward?

If you need any more information please let me know.

Thanks,
Liam

**Comment by jonathanleather** [comment]
Hi @liam-lagay-14 

Your colleague is correct, this is due to the sandbox.

The obligations endpoint is stateless. 
So therefore, any VAT returns you submit for a particular period will not be reflected in the obligations for that user. The obligations endpoint will just return the same canned response.

We are looking at improving the canned responses for this endpoint, so that you can simulate a journey. 

You're not the first to raise this issue, so I will take this back to the team to see if we can prioritise this work.

Cheers
Jon
