### ISSUE TITLE
VAT Obligations status

### ISSUE THREAD

**Issue by khabut** [hmrc/vat-api#196]
We have made a request to get obligation using status=O but it now always returns F and O. Is this a bug or a change in the way this works. Also at what point does the obligation get moved to F.

**Comment by jacobbrownlow** [comment]
Hi @khabut 

Apologies for the late reply.

In production VAT Obligations are created on the first day of the given period. They are given the status `O` for Open.

When a user successfully submits a VAT return for this period the status will be updated to `F` for Fulfilled.

In sandbox the responses to GET VAT Obligations are canned and do not change depending on whether you submit a return. We are just released new test scenarios for this endpoint which are designed to give a more realistic journey. 

However because they are canned, using the status parameter, e.g. `status=O`, will have no effect in the sandbox environment.

Regards, Jacob

**Comment by macgrewal** [comment]
Hi @khabut, Hopefully @jacobbrownlow's response above has answered your query. I will close this issue but feel free to re-open if it doesn't.
