### ISSUE TITLE
Can't connect to the View VAT Return API

### ISSUE THREAD

**Issue by Comtass** [hmrc/vat-api#200]
I have managed to connect to the get obligations API and to post a VAT return, The next stage of my journey is to view VAT returns but it isn't working for me. Hopefully it will be something simple.

Here is the Postman of what I am trying to achieve:-
![image](https://user-images.githubusercontent.com/39489338/42878241-3be6b534-8a84-11e8-88c5-2015c94aebe8.png)

**Comment by jacobbrownlow** [comment]
Hi @Comtass 

Can you try again with the URL
**https:/**/test-api.service.hmrc.gov.uk/organisations/vat/ VRN /returns/#002

Regards, Jacob

**Comment by pwatts001** [comment]
Hi @jacobbrownlow,

I'm having a similar issue here.

My URL is: https://test-api.service.hmrc.gov.uk/organisations/vat/666712116/returns/%23003

I'm getting a 404 response with no content/error message. If I add an extra digit to the period key (->%230034) I get the PERIOD_KEY_INVALID message. 

I certainly have write:vat permission and I'm trying to view a return that has been submitted as per the obligations API.

Does this API only work for returns that have also been submitted by the MTD API?

Thanks,
Phil

**Comment by jacobbrownlow** [comment]
Hi @pwatts001 

Sorry for the late reply.

404 with no error implies you've got no return with a matching vrn and periodkey.

If you were to hit an incorrect URL/resource the response would be
```json
{
    "code": "MATCHING_RESOURCE_NOT_FOUND",
    "message": "A resource with the name in the request can not be found in the API"
}
```
%23 = #, so %230034 would be `#0034`, which is invalid because you can only have 4 alpha numeric characters.

For your permissions, it may be worth trying **read:vat+write:vat** if you already haven't.

_Does this API only work for returns that have also been submitted by the MTD API?_ Correct, it will not return legacy returns in Production. In sandbox it will return anything that has been submitted, we don't currently clear down returns.

Regards, Jacob

**Comment by daveowensuk** [comment]
I am also trying to get the vat api to work. I can grant and gain access but when I try and get obligations I am seeing an error stating:

![image](https://user-images.githubusercontent.com/11569617/48435202-d3795680-e773-11e8-8b08-4de6e5f46955.png)

Maybe it is actually down at the moment but seems odd.

Has anyone else seen this error - I will try again tomorrow in case the service is genuinely down.
