### ISSUE TITLE
Test header values when submitting a return

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#251]
When I use the test header to force an invalid VRN error, I get VRN_INVALID returned. When I do the same with the period key I get PERIOD_KEY_INVALID returned. 

When I do it with the INVALID_PAYLOAD error however I just get this:

`{"code":"INVALID_REQUEST","message":"Invalid request"}`

The only reason why I know what error happened is because I forced it to happen. If I was relying on information returned from the server then I wouldn't have a clue, nor could the error really be used in any way to present anything readable to the user than might actually be useful.

**Comment by seurrep** [comment]
Also with the INVALID_ARN test header value the server appears to return 500 (internal server error) rather than any JSON detailing the nature of the error.

**Comment by jacobbrownlow** [comment]
Hi @seurrep  

With the Submit VAT Return endpoint there is actually no need to use the Gov-Test-Scenarios. In fact, if developed again, we wouldn't include them.

You can test invalid VRN, Period Key and Payload manually just by submitting bad data.

Because the scenario doesn't have a real error, it throws INVALID_REQUEST without an explanation.

Here is an example where a real error is triggered:
```json
{
    "code": "INVALID_REQUEST",
    "message": "Invalid request",
    "errors": [
        {
            "code": "MANDATORY_FIELD_MISSING",
            "message": "a mandatory field is missing",
            "path": "/vatDueSales"
        }
    ]
}
```

I'd suggest to create the errors manually for a realistic error response.

With regards to the INVALID_ARN error, I believe this is a back-end response that we are not surfacing up to the end user. I think the choice was to show a 500 error instead, which could be investigated if it occurs in Production. I'm not sure why the previous development team decided to expose this scenario to the end users to be honest. I can query this to the team, but I would imagine the solution would be to remove the Gov-Test-Scenario for it. 

Regards, Jacob
