### ISSUE TITLE
Possible incorrect error when getting a VAT return using invalid period key

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#255]
Viewing a VAT return using a valid period key appears to work acceptably. However if I pass in an invalid period key (in this case I just used the value 'XXXX' in the place of a valid value (so the URL is "https://test-api.service.hmrc.gov.uk/organisations/vat/666294476/returns/XXXX") returns 404.

Shouldn't this be returning 400 (PERIOD_KEY_INVALID) as per the documentation?

**Comment by jacobbrownlow** [comment]
Hi @seurrep 

`PERIOD_KEY_INVALID` refers to a period key that does not mean the correct format, which is 4 alpha-numeric characters, and occasionally beginning with a #.

Valid examples: 18AD, 18A1, #001, or XXXX

XXXX is a valid period key, it just doesn't exist (unless you submit it first), which is why the 404 is returned.

Try 12345 or XXXXX to retrieve this error.

Regards, Jacob

**Comment by JeeBeePee** [comment]
I think this should be re-opened. The 404 returned (in the sandbox at least) is not accompanied by a MATCHING_RESOURCE_NOT_FOUND or NOT_FOUND error. The message body is empty.
