### ISSUE TITLE
Submit VAT return for period response documentation

### ISSUE THREAD

**Issue by RobertMarczycki** [hmrc/vat-api#27]
Hi,

https://test-developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_submit-vat-return-for-period_post_accordion does not document response payloads for VAT submissions; should it be assumed tha the payload will always have a constant number of fields as in the response below? 
{
    "processingDate": "2018-01-16T08:20:27.895+0000",
    "paymentIndicator": "BANK",
    "formBundleNumber": "256660290587",
    "chargeRefNumber": "aCxFaNx0FZsCvyWF"
}
I believe a question related to the meaning of the fields was already raised.

Thanks,
Robert

**Comment by hicnar** [comment]
Robert,
Here is some more information describing the result returned after successful vat submission
processingDate - time stamp for when message was processed in the system
paymentIndicator- this can be either DD or BANK or not present at all, when return is a debit i.e. Trader has to pay and Direct Debit is set up for such trader we would return DD, when return is a claim i.e. credit where HMRC will pay out and bank details are present on master data then BANK indicator is sent, for NIL returns, or where bank / DD data does not exist nothing will be sent
formBundleNumbe - unique number representing Form Bundle, the system creates forms to store return data, those are held in form bundle that is unique within the system 
chargeRefNumber  – this represents charge reference number, this number is only derived in case where charge is a debit, intention was to pass it to back end so that trader can make payment against this number, however I believe that business does not want to disturb current status quo where traders use VRN to pay

Hope this makes things clearer

K.

**Comment by rtomanek** [comment]
Hi Krzysztof,

 thank you for this, we now have much more information.

 We would still have a few more questions around the overall workflow, etc. and I am not sure whether github issues is conducive to having an efficient discussion here. @hicnar I was wondering if you would able to reach out to me via the email address published on the profile page so that we could set up a quick conf call.

Pozdrawiam,
Robert
