### ISSUE TITLE
Payment data- test dates?

### ISSUE THREAD

**Issue by adamdavi3s** [hmrc/vat-api#286]
Hi All,
Can anyone let me know what dates they are using to retrieve payments and liabilities? 
Is there any data there as standard for a test organisation or do we need to submit a return to create the liability?
If so how do we then submit payment data to return?

I am just getting "no data can be found"

have tried the dates given in this link as well as a wide range of dates for 2016-2018
https://github.com/hmrc/vat-api/issues/252

**Comment by jonathanleather** [comment]
Hey @adamdavi3s 

The payments and liabilities endpoints are stateless so there is no set up required. (no need to submit a vat return etc)

Due to the endpoint returning canned data you need to pass in one of the gov-test-scenario headers along with your GET request. Using the dates mention in that issue you have referenced and passing in  one of the gov-test-scenarios should return you a successful result.

For reference the gov-test-scenarios can be found on the specific endpoints documentation towards the bottom.

Let me know if you continue to have issues.

Cheers
Jon

**Comment by adamdavi3s** [comment]
@jonathanleather  Thank you! Sorry read it as an optional header and thus ignored it.
Makes perfect sense thank you :)
