### ISSUE TITLE
ChargeRefNumber

### ISSUE THREAD

**Issue by seurrep** [hmrc/vat-api#298]
There have been a few occasions now where the ChargeRefNumber field has not been included in the output from submitting a return. This is despite documentation detailing it as one of the fields that ought to be returned. Less than an hour ago for example I got this returned from the API after submitting a VAT return:

`{"processingDate":"2018-10-10T11:34:19.458Z","paymentIndicator":"BANK","formBundleNumber":"113021070647"}`

Is this omission intentional?

**Comment by MarkAKelly** [comment]
Hi @seurrep,

The documentation states that the `chargeRefNumber` field is optional, and will only be returned if 'netVatDue' is a debit.  The documentation also states that if `paymentIndicator` is 'BANK' (and therefore not 'DD'), then the 'netVatDue' is a credit, in which instance you would not receive the `chargeRefNumber`.

Hope this helps.
Mark

**Comment by lukaszszczygiel-sage** [comment]
I also spotted that the chargeRefNumber is missing. From the other hand I was able to recive chargeRefNumber even if I get `"paymentIndicator":"BANK"`. I send `{
  "periodKey": "#898",
  "vatDueSales": "144463.83",
  "vatDueAcquisitions": "0",
  "totalVatDue": "144463.83",
  "vatReclaimedCurrPeriod": "39656.89",
  "netVatDue": "104806.94",
  "totalValueSalesExVAT": "873862",
  "totalValuePurchasesExVAT": "227144",
  "totalValueGoodsSuppliedExVAT": "29954",
  "totalAcquisitionsExVAT": "515",
  "finalised": true
}
` and recive `{"processingDate":"2018-10-12T12:12:32.821Z","paymentIndicator":"BANK","formBundleNumber":"836393765263","chargeRefNumber":"WWXdW9hcST4EP4qF"}`

**Comment by MarkAKelly** [comment]
@lukaszszczygiel-sage is this an issue you are having with the sandbox environment or is it a live issue?

**Comment by lukaszszczygiel-sage** [comment]
@MarkAKelly Sorry for late answer. This is issue with the sandbox env

**Comment by jacobbrownlow** [comment]
Hi @lukaszszczygiel-sage 

Just to clarify `paymentIndicator` can be missing. The documentation provided states:

`paymentIndicator`: Is DD if the netVatDue value is a debit and HMRC holds a Direct Debit Instruction for the client. Is BANK if the netVatDue value is a credit and HMRC holds the client’s bank data. Otherwise not present. Limited to the following possible values: DD, BANK

`chargeRefNumber`: The charge reference number is returned, only if the netVatDue value is a debit.

Additionally we have updated the sandbox environment to not return `chargeRefNumber` if the `paymentIndicator` is "BANK".

Regards, Jacob

**Comment by lukaszszczygiel-sage** [comment]
@jacobbrownlow Thanks for the confirmation the on sandbox the values are randomised and also for amending the sandbox env
