### ISSUE TITLE
How to check  vat return API for individuals

### ISSUE THREAD

**Issue by pp07** [hmrc/vat-api#359]
Hii,
Good Morning ,

Anyone has idea,How to check  vat return API for individuals in sandbox,because HMRC gives only url for organization but not for  individuals in vat documentation.

If anybody knows please guide me.

Thanks in advance

**Comment by jonathanleather** [comment]
Hi @pp07 

You would hit the existing `organisations/vat` URL, there isn't a separate one for individuals. (I understand the `organisations/vat` is misleading, rest assured this has been raised)

Within regards to testing in sandbox you would create a test user using the `Individuals` endpoint rather than the normal `Organisations`. As it stands however I don't believe the `/create-test-user/individuals` is configured for MTD-VAT. I have raised a story for the team to investigate and if possible, update the endpoint to enable testing with individuals against the VAT-API in sandbox.

Cheers
Jon
