### ISSUE TITLE
Retrieve VAT liabilities The remote endpoint has indicated that no data can be found in sandbox

### ISSUE THREAD

**Issue by kontrasenyas** [hmrc/vat-api#392]
* **I'm submitting a ...**
  - [x] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [ ] Feature request
  - [ ] Support request

I'm trying to test  **Retrieve VAT liabilities** endpoint in sandbox environment but no data returned. 

This is the get request:
https://test-api.service.hmrc.gov.uk/organisations/vat/666192484/liabilities?from=2018-01-01&to=2018-12-31

* **What is the current behaviour?**
Status: 404 Not found

```
{
    "code": "NOT_FOUND",
    "message": "The remote endpoint has indicated that no data can be found"
}
```

* **What is the expected behaviour?**
```
{
  "liabilities": [{
    "taxPeriod": {
      "from": "2017-04-06",
      "to": "2017-07-06"
    },
    "type": "VAT ...",
    "originalAmount": 6000.00,
    "outstandingAmount": 100.00,
    "due": "2017-07-06"
  }]
}
```

**Comment by jacobbrownlow** [comment]
Hi @kontrasenyas 

The VAT payments and liabilities endpoints are canned data and require the correct test header to be supplied in order to retrieve data. Additionally these endpoints filter by date (even in test) and therefore the correct dates must be supplied to get the expected response.

Please review the test section of the documentation
![image](https://user-images.githubusercontent.com/35334115/51311233-5baffc80-1a40-11e9-82dd-b8f6ba9edf19.png)

Thanks Jacob
