### ISSUE TITLE
Using Postman for Auth Testing

### ISSUE THREAD

**Issue by AndyYouens** [hmrc/vat-api#400]
Trying to use Postman for the 1st time :-(

Can someone please confirm I am using the right URLs for the OAUTH token

![image](https://user-images.githubusercontent.com/20203631/51386469-6048e380-1b1a-11e9-8126-3d10e51b563b.png)

Your help appreciated

**Comment by jacobbrownlow** [comment]
Hi Andy

I'm not sure what you are doing in Postman but normally you build up a request like so:
<img width="645" alt="51384306-d8f87180-1b13-11e9-8f11-da3e3e72f22d" src="https://user-images.githubusercontent.com/35334115/51396605-4a95e700-1b37-11e9-8bf3-d666d2d9b3f9.png">

**Comment by AndyYouens** [comment]
Hi jacob

I'm trying to prove there is nothing wrong with our coding that worked for the past month, but now fails with a 404-bad request when asking for the auth token.

In postman, i'm trying to retreive obligations, and using the authorisation tab to setup the oauth details, so just wondering if these settings above were correct?

using them returns the error
{"error":"invalid_request","error_description":"redirect_uri is invalid","state":""}

thanks for your help.

**Comment by AndyYouens** [comment]
what is the code parameter there Jacob?

**Comment by jacobbrownlow** [comment]
Hi Andy

`client_id`, `client_secret` and `redirect_uri` are just what is defined in your application details on the Developer Hub
 
`code` is the oauth code returned in the frontend URI when you complete the "grant authority" journey

Could I ask that if you are continuing to have trouble with the auth flow, could you please email the Software Developers Support Team at SDSTeam@hmrc.gsi.gov.uk, because they will be in a better position to help you with auth issues. We try to help but our focus is really on the vat-api. 

Regards, Jacob
