### ISSUE TITLE
Identify a connection

### ISSUE THREAD

**Issue by DDSebastian** [hmrc/vat-api#421]
* **I'm submitting a ...**
  - [ ] Bug - API
  - [ ] Bug - Documentation
  - [ ] Improvement
  - [X] Feature request
  - [x] Support request

* **What is the current behaviour?**
Our software allows a user to have multiple connections to HMRC api.
Currently there is no way to uniquely Identify a connection when the OAUTH authorization process is finished because no details are passed back to the calling service.

* **What is the expected behaviour?**
Is it possible to return a unique id that identifies the connection made by the user? The user ID or the VRN would be perfect, but if that is not the case, there must be some id that can be returned by HMRC api in order to identify the connection. These can either be returned via the header or parameters during the callback process.
If this is absolutely not possible, is there an API endpoint which can be used in order to retrieve information regarding the user once connection has been established? e.g. the name, vrn, etc.?

* **Other Information**
Agent 1 would like to submit VAT MTD for User 1 and User 2. 
In this case he will needs to create two connections in our software. In a year time, or when the agent needs to re-submit the a new VAT MTD, most probably, he will need to reauthorize the connection, but we do not want him to create two new connections. We would like to be able to know that the connection the agent is making was already been used in the past so we replace the authorization keys of the old connection and not having the user to delete the old connection manually.

**Comment by DDSebastian** [comment]
Any feedback on this?

**Comment by scottylace** [comment]
Hi @DDSebastian apologies, we'll get a reply back to you soon.

**Comment by scottylace** [comment]
Hi @DDSebastian, 

Regarding the points below

>* * What is the current behaviour?
Our software allows a user to have multiple connections to HMRC api.
  Currently there is no way to uniquely Identify a connection when the OAUTH authorization process is finished because no details are passed back to the calling service.
>**What is the expected behaviour?**
  Is it possible to return a unique id that identifies the connection made by the user? The user ID or the VRN would be perfect, but if that is not the case, there must be some id that can be returned by HMRC api in order to identify the connection. These can either be returned via the header or parameters during the callback process.

As mentioned on the following developer hub page: [Developer Hub Authorisation](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints#auth-endpoint-syntax), you can supply a unique "state" query parameter when calling the https://test-api.service.hmrc.gov.uk/oauth/authorize endpoint, the "state" query parameter supplied is then returned back in the redirect URL. I believe this could be the solution you are after. 

Regarding: 

>**Other Information**
  Agent 1 would like to submit VAT MTD for User 1 and User 2.
  In this case he will needs to create two connections in our software. In a year time, or when the agent needs to re-submit the a new VAT MTD, most probably, he will need to reauthorize the connection, but we do not want him to create two new connections. We would like to be able to know that the connection the agent is making was already been used in the past so we replace the authorization keys of the old connection and not having the user to delete the old connection manually.

The agent client relationship is managed on the Government Gateway, therefore when calling the HMRC authorisation endpoint and entering Government Gateway credentials it would be the agents details entered. When calling a VAT endpoint you'd supply the access token received from authorising the agents details. 

I hope that helps clarify a bit more detail.

**Comment by DDSebastian** [comment]
Hi,

The problem is not in identifying the connection from  our end, but rather identify the connection from your end. 
We need to know that a particular connection has been already been used and thus the identifier has to come from the HMRC API and not from our end.
If I understood correctly, each connection to HMRC can only be linked to 1 VRN. Would it be possible to return this value when connecting to HMRC?

**Comment by scottylace** [comment]
Hi @DDSebastian, 

Can you confirm exactly what you mean by a connection? Are you referring to managing HTTP connections? 

Thanks, 

Scott.

**Comment by DDSebastian** [comment]
Hi @scottylace ,

By connection I mean an api connection to HMRC.
So after the authorization process has ended we would like to be able to identify the person connected to the api. In Short, we would like to have either the VRN number, which is a public information, or the username that generated the connection returned as part of the access token response.

**Comment by DDSebastian** [comment]
Hi,

Instead of the above, Since all vat mtd endpoints require the VRN, is there a way to retrieve the VRN once connection has been established?

Thanks.

**Comment by moonlitknight** [comment]
@DDSebastian  Look again at the `state` parameter. That is where you will provide the unique ID, which will be reflected back to you as part of the redirect URL.
