### ISSUE TITLE
Fraud Prevention Headers

### ISSUE THREAD

**Issue by KenRandall** [hmrc/vat-api#427]
When submitting an issue please try to provide the following information:

* **I'm submitting a ...**
  - [x ] Improvement
 
* **What is the current behaviour?**

 We have no way of testing these headers. This means that our software can suddenly fail when these are turned on.

* **What is the expected behaviour?**

Need a way of testing these headers.

* **Other information** (e.g. detailed explanation, screenshots, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I am currently submitting these headers in the live system but have no way of knowing if they will be accepted as they are crrently being ignored.

Regards,

Ken

**Comment by Yottskry** [comment]
HMRC's support for these headers has been shockingly woeful. They claim they want to engage with the development community and yet have failed to satisfactorily answer any of the questions about these stupid headers. They don't provide a mechanism for testing the headers in a live environment, offer no feedback about them in the sandbox and haven't answered the very simple question of what happens if the headers are incorrect. To top it all, after waiting months for a response we get an email that essentially says "We're going to support you by supporting you".

Useless.

**Comment by konradwudkowski** [comment]
hi @KenRandall We are looking at the best solution for allowing you to test your header compliance. We will update here as soon as we know the details.

We do not plan, immediately after April, to reject messages at API level for noncompliance with this requirement. But we expect all vendors to be compliant, and we will identify and work with any noncompliant vendors to ensure services are made compliant as quickly as possible. We will, later in the year, consider whether we will reject messages for noncompliance with the fraud prevention headers at API level.

**Comment by KenRandall** [comment]
Thanks. Good news.

Ken
