### ISSUE TITLE
Fraud Prevention & GDPR

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#456]
Where do we stand as software developers gathering information from a customer's PC and passing this on to a third party (HMRC) with regards to GDPR?

Our software runs as a desktop app on our customer's own pc hardware.
Some of the headers require us to send user names, ip address of other pc's available to the user's pc on the network, mac addresses etc.

Are we duty bound to notify our customer's that this will happen?
Does the customer have the right not to provide this information.
If the customer does not want to provide this information, how does this affect their VAT submission?
Any other questions other developers want to add, please feel free to.

**Comment by MKoppJones** [comment]
I second this actually. Good point to bring up

**Comment by Coolkama** [comment]
I agree, it is totally unreasonable to expect this sort of data-mining from a users site.
it is also highly questionable how most of this information would even be of use!


How can you justify the requirement of some of this data for a VAT return?

Also if this data has to be submitted with every API call, the API calls themselves will potentially take forever to call, but only due to gathering up to the minute data for these headers!

**Comment by ruffle-b** [comment]
I do agree that the required headers are far too broad and intrusive.

I wondered what to put in the Gov-Client-Local-IPs field as it doesn't seem to permit CIDR notation and expanding 10.0.0.0/8 would result in a rather large header!

**Comment by adamdavi3s** [comment]
I've simply included this in our documentation.

Don't forget we are talking business to government here where the GDPR regulations are not as stringent as customer to business

**Comment by anyolejoe** [comment]
Our organisation is also not comfortable about the detailed info required about a user's workspace and environment in order to use APIs that have been mandated in MTD, such as VAT. It feels a bit like being required to produce spyware on behalf of HMRC.

**Comment by GrahamHDawson** [comment]
From the developer email on 27th Feb 2019

"Following feedback from some of you and in order to ensure the legal position in relation to providing this information is clear for all concerned,  secondary legislation has been laid in parliament which comes into force on the 19th March 2019. The legislation can be found here http://www.legislation.gov.uk/uksi/2019/360/made. The effect of the secondary legislation will be to explicitly require developers to collect and supply fraud header metadata. The developer will be the data controller of that data by virtue of Section 6 of the Data Protection Act 2018, which supplements the definition of "controller" found in Article 4(7) of the GDPR and provides that the person who is obliged to process data under a statutory obligation is the controller. This provision replicates what was section 1(4) of the Data Protection Act 1998"

So not only do we have to do it, but we're responsible for it as the controller under GDPR 
We'll definitely be displaying some sort of message to indicate what data we're obliged to collect on HMRC behalf and that this data is not stored in any way but just posted to HMRC
