### ISSUE TITLE
Submitting a successful vat return

### ISSUE THREAD

**Issue by MrSent** [hmrc/vat-api#504]
Having set up test users for VAT returns, is there a way I can simulate a successful VAT return? Simulating the errors is fine. It would be nice if they were standardised for example INVALID_VRN and VRN_INVALID. Why are there 2? Surely they're the same? Anyway, if I do a submit, I would like to be able to simulate a successful response so I can test this easily within my system. Either I've missed something or there isn't a way.

**Comment by james-work-account** [comment]
Hi @MrSent - can you please provide some more information so we can help diagnose this issue? Specifically:

- Route hit (& HTTP verb used)
- Headers used
- Request body

If you are using the correct headers, without a GovTestScenario, and a correct body, then it should work.

**Comment by MrSent** [comment]
The route is /organisations/vat/{vrn}/returns where {vrn} is my test user vrn number. The headers are correct for what I need to send across, so:
Accept: application/vnd.hmrc.1.0+json
Content-Type: application/json
Authorization: <my bearer token>

My scope is write:vat

So when I submit, I want to be able to simulate a successful submission. The Gov-Test-Scenario's available for vat submission are:
INVALID_VRN
INVALID_PERIODKEY
INVALID_PAYLOAD
DUPLICATE_SUBMISSION
TAX_PERIOD_NOT_ENDED

That's great but I want to see what happens when I submit successfully. If I create a test user it seems to me that I can only submit once and then I need to create a new test user. Am I missing something?

**Comment by james-work-account** [comment]
You can only submit once per user for a given period. Either changing the periodKey or user will work, otherwise you will get a DUPLICATE_SUBMISSION error.

For example, POSTing the following once will be successful (with a valid VRN, access token, etc):

```
{
  "periodKey": "0319",
  "vatDueSales": 100.00,
  "vatDueAcquisitions": 100.00,
  "totalVatDue": 200.00,
  "vatReclaimedCurrPeriod": 100.00,
  "netVatDue": 100.00,
  "totalValueSalesExVAT": 500,
  "totalValuePurchasesExVAT": 500,
  "totalValueGoodsSuppliedExVAT": 500,
  "totalAcquisitionsExVAT": 500,
  "finalised": true
}
```

However, POSTing the exact same periodKey will fail with the following error:

```
{
    "code": "BUSINESS_ERROR",
    "message": "Business validation error",
    "errors": [
        {
            "code": "DUPLICATE_SUBMISSION",
            "message": "The VAT return was already submitted for the given period."
        }
    ]
}
```

To POST again for this user, you'd need to change the period they are submitting for. I believe in the Sandbox, it just needs to be any combination of four characters which is unique to that user.

Also to clarify, you shouldn't include any GovTestScenario headers if you want to simulate a successful response.

I hope this helps.

**Comment by MrSent** [comment]
Ahh ok, I will try with a different period key.
