### ISSUE TITLE
Which Grant type use for Live environment

### ISSUE THREAD

**Issue by pp07** [hmrc/vat-api#559]
Please help me

I got following error  when i try to accessing Live WEB-API of vat

{"error":"invalid_request","error_description":"code is required for given grant_type"}

thanks in advance

**Comment by pp07** [comment]
Now i am using grant_type=authorization_code

**Comment by pp07** [comment]
Please give suggestion it urgent

**Comment by ma3574** [comment]
Hi @pp07 

The VAT API Development team do not manage the Authorisation with hmrc. Hence we are unable to provide live support for this issue. 

However we can direct you to the documentation here:
https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

If you read under the _***Getting an OAuth 2.0 access token***_ section you will see the list of errors and what causes them. If this doesn't resolve your issue please contact SDSTeam@hmrc.gov.uk for live supprot

**Comment by slczyk** [comment]
@pp07 Make sure that you're setting request headers (Accept, Content-Type, etc. ). I remember that I was running into a similar problem on the test. Not setting them was causing the invalid_request for me.

**Comment by pp07** [comment]
@slczyk  
yes i am setting both accept and content type headers but still i got this error

**Comment by pp07** [comment]
Actual problem is when i am hit first request to HMRC then it gives me auth_id 

after that using that auth_id hit the second url of oauth/token that time it throws error for grant_type. please help me.

**Comment by Yottskry** [comment]
The error message you mention is on this page:

https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints

It says it could mean "Code is missing (for example because authorisation failed in step 2)"

Are you including the authorisation code received from HMRC when you make your second call?

e.g.: curl -X POST --data \
'client_secret=[YOUR-CLIENT-SECRET]&client_id=[YOUR-CLIENT-ID]&grant_type=authorization_code&redirect_uri=[YOUR-REDIRECT-URI]&code=[AUTHORIZATION-CODE]' \
https://test-api.service.hmrc.gov.uk/oauth/token

**Comment by Yottskry** [comment]
Also, do you have live credentials? HMRC don't give you them until you've demonstrated your software in Sandbox mode to them. If you're calling the live endpoint you need live credentials. In your HMRC developer account go to "View all applications" and ensure that your application has "Production" against the "Environment" and not "Sandbox". You cannot use Sandbox credentials against the production URL.

**Comment by pp07** [comment]
@Yottskry 
Yes. we have production credentials.

My requested url is
https://api.service.hmrc.gov.uk/oauth/authorize?response_type=code&redirect_uri=redirect_url&scope=read:vat&client_id=client_ID

and we got response url is
oauth/start?auth_id=5cadae5e2800002600526c25
please if you know about it

**Comment by Yottskry** [comment]
That auth_id is not the authorization code. You need to actually load the url in a browser so that the user can log in. Once the user logs in, there's a redirection to a success page that contains the auth code in the title. You need to send THAT code as the authorization code when you make the request for the access token.

So, direct a browser to your URL and then log in with your HMRC username and password, then get the authorisation code from the final page (title: "Success code=xxxxxxxxxxxxxxxxxxxxx") and then request the access token using this code.

**Comment by pp07** [comment]
@Yottskry 

Their any procedure after getting production credentials to access live data?

**Comment by Yottskry** [comment]
I don't understand what you're asking.

**Comment by Yottskry** [comment]
You can only access live data if you have a live Government Gateway account - i.e. you are a business making VAT returns. There's no way to test on the live gateway, but if it works in Sandbox then it *should* work in Live.

**Comment by pp07** [comment]
@Yottskry 

Ok thank you
