### ISSUE TITLE
Separate production application per client in HMRC developer Hub to use HMRC VAT functionality via our software

### ISSUE THREAD

**Issue by rajitha0007** [hmrc/vat-api#561]
Hello all, 
Recently, we have received the VAT production approval for our software from DRM team and now, we are in the phase of creating the production applications in HMRC developer Hub. 
Some of the communications with HMRC indicated that each software Vendor can only create a single production application in HMRC Developer Hub and all the clients of that software vendor needs to use that application for the VAT submission to HMRC. But, this is not working for us due to below given reasons;

Our product is a “On Premise” software solution and our clients have their own IT teams to manage the day-to-day maintenance of the locally installed software solution. their preference is to create and maintain separate production application in HMRC Developer Hub. This will allow them to maintain their own credentials (e.g. Client ID, Client secret and URI) without sharing those information with us (software provider). As a software provider, we are also not in a position to maintain credentials of multiple clients due to several reasons. 

Another issue is each Application created in the HMRC Developer Hub can support maximum 5 different URIs and 5 client secrets only.  So, the single production application per software vendor is not working for us due to we have multiple clients who are planning to use this functionality. 
Can you please confirm, is there any restriction of creating separate production application for each of our clients to use HMRC VAT functionality implemented in our software solution? 
If any other firm is also in the similar situation, how did you handle this situation/ issue ? 
Thanks you all in advance and I look forward to hear from you soon. 

Cheers
RJ

**Comment by markogrady** [comment]
I have the same situation with other app and other API. Sometime the API says each client has to create a developer account and get their own API details, because the contract is with them.

Depending on what HMRC say, if it ends up really unflexible, you could create one server that acts as a proxy to deal with the auth. You send the return url as the proxy server which then redirects the detail to clients installed url.

**Comment by cb-rfk** [comment]
I think you could have discussed this during your product demo: certainly the very helpful person we demo'ed to would have advised us on this kind of issue.

Do you still have contact details for that person?

**Comment by rajitha0007** [comment]
thanks, @markogrady. and @cb-rfk 
I have discussed this during the demo and he suggested to discuss this with SDS team. I have already sent an email to SDS team. But we are still waiting for their response. :(

**Comment by JeeBeePee** [comment]
I asked the same question and was told that each customer who wants a deployed solution with their own HMRC Dev Hub account will have to do a demo to SDS to get their production credentials. This is similar to how many API providers operate, except they have a more formal conformance testing process rather than the loose "demo" undertaken to SDS.
