### ISSUE TITLE
Fraud prevention header specification – compliance

### ISSUE THREAD

**Issue by Martin-d79** [hmrc/vat-api#562]
Hi,

Do i need to set the headers for all my API calls including OAtuh API?

Thanks in advance.
Martin

**Comment by Martin-d79** [comment]
Is their list of headers that can't be empty?
I couldn't get the Mandatory header fields that is absolutely required.

Thanks,
Martin

**Comment by GrahamHDawson** [comment]
Yes I'd like an answer to this as well.

The documentation for the **MTD VAT API** has links to the Anti-Fraud header page, but the reference guide to the oAuth side of things does **not** have a link to the Anti-Fraud header page.

So in our case we've left the headers off the /oauth/token endpoint when getting the access token or refresh token.
It would be nice to have confirmation that this is correct.

**Comment by LukeHirst** [comment]
I would also like a response to @GrahamHDawson question. 

We've added FPH to all the api calls excluding any that are used for the Oauth journey (retrieving tokens and etc).

Clarification on this and an update of the api documentation would be appreciated.

**Comment by Yottskry** [comment]
I've done the same as both of you - no headers on the oAuth calls but headers on anything going to an MTD endpoint.

Would be nice to have a response to this question. And every other unanswered question....

**Comment by Martin-d79** [comment]
We regard this as a lot of work at short notice and my boss has asked me to complete this is in my spare time! If I could get answers to my questions I would really appreciate it.

**Comment by Yottskry** [comment]
Are you making a desktop app or a web app (and what sort? Via server, etc?)
What headers are you having trouble with? The advice for even mandatory headers that you are unable to collect because of restrictions on the sending device (permissions, security, no available API call, etc) is to leave them blank or omit them entirely.

HMRC's guidance says that they will not reject submissions for incorrect headers at this stage *but* we should try in good faith to be compliant.

When you have something you think it suitable, email HMRC with the raw headers (captured in something like Telerik Fiddler) and they will tell you they are compliant and/or query any headers that are missing or incomplete.

**Comment by Martin-d79** [comment]
thanks Yottskry, they will not reject the submission but are we liable for the 3K fine?!

We have sent them a sample header so we will see what they come back with.

**Comment by Yottskry** [comment]
> but are we liable for the 3K fine?!

I don't think so, and, reading between the lines, I think they will work with you to make the headers compliant rather than just immediately fine us. The emails we've received along the way do seem to imply that. This from 01/02/2019 says:

`We will help you to build and manage software that is compliant to the HMRC fraud prevention header specification, by: 
•	Providing support and guidance to your questions sent to sdsteam@hmrc.gsi.gov.uk or posted to GitHub https://github.com/hmrc/vat-api/issues .
•	Checking your software compliance. This will either be as a review before software production credentials are approved, or arranged with you if production credentials have already been granted.  
•	Conducting post production checks on live transactions from customers using your software and work with you to resolve any issues.
We will help you to build and manage software that is compliant to the HMRC fraud prevention header specification, by: 
•	Providing support and guidance to your questions sent to sdsteam@hmrc.gsi.gov.uk or posted to GitHub https://github.com/hmrc/vat-api/issues .
•	Checking your software compliance. This will either be as a review before software production credentials are approved, or arranged with you if production credentials have already been granted.  
•	Conducting post production checks on live transactions from customers using your software and work with you to resolve any issues.
`

**Comment by konradwudkowski** [comment]
hi Martin-d79,
you don't need fraud prevention headers for OAuth calls but you do need them for the following API: https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0

**Comment by GrahamHDawson** [comment]
@Martin-d79 
Please could this information be added to the GitHub FAQs and the API documentation
