### ISSUE TITLE
Error reporting API for user that leaves the beta but attempts submission

### ISSUE THREAD

**Issue by PaulTaylorSage** [hmrc/vat-api#57]
I am creating user stories covering users who are taking part in the MTD for VAT beta and have a couple of scenarios where I need to know the errors that will be returned from HMRC.

1 - User of accounting software has been accepted onto the beta
2 - The user submits a VAT return via the new API and is accepted by HMRC 
3 – User leaves the beta program and submits next VAT return via the Government Gateway
4 – User attempts to submit a VAT return via the MTD API
5 – What error will be returned by the MTD API?

**Comment by jacobbrownlow** [comment]
Hi @PaulTaylorSage 

Apologies that this issue was overlooked.

What exactly is meant by "leaves the beta program"?

As far as the team is aware: a user (tax payer) may enrol for MTD but we are not aware of any mechanism to de-enrol. A vendor application can subscribe to the service vat-api and unsubscribe at any time.

For more information about enrolling and de-enrolling (if possible) I would advise you to contact the Software Developers Support Team by emailing SDSTeam@hmrc.gsi.gov.uk

Regards, Jacob
