### ISSUE TITLE
When are Open obligations available?

### ISSUE THREAD

**Issue by ddaddy** [hmrc/vat-api#580]
When are open obligations meant to be available?
I'm sure I read they are only available once the period has ended, but I can't find that text now.

When I first got my production keys 2 weeks ago, no obligations were returned for my VAT account (As expected). However today I now have an open obligation for period `19B1` ending `2019-05-31`. Has a change been made to when open obligations are returned?

**Comment by GrahamHDawson** [comment]
Don't know the exact answer to your question **but** they've recently introduced an error on the submit endpoint TAX_PERIOD_NOT_ENDED - so that suggests open obligations will be shown before the period has ended.

**Comment by markogrady** [comment]
I have issues with certain Obligation not populating. The period has
definitely started and still no returns. I get user to log in to the HMRC
to prove that there are no obligations there. I will have a look but, I'm
sure one person was waiting over 2 weeks. The only response I got from HMRC
look at this link

See Notes
https://developer.service.hmrc.gov.uk/guides/vat-mtd-end-to-end-service-guide/documentation/obligations.html#receive-obligations-and-submit-a-vat-return


 or contact live services but you need the clients approval that you can
ask questions, which proves a problem each time, because the client spends
ages and can't get through so you end up leaving it til the returns appear.
It would be good if the dev department could liase with the live services,
to really try and nail issues.

https://www.gov.uk/government/organisations/hm-revenue-customs/contact/vat-online-services-helpdesk

**Comment by mtd-api-team** [comment]
In this instance the expected behaviour is as stated in the service guide.

There are unique cases relating specifically to VAT customers who have been migrated over from an existing VAT enrolment to a new MTD VAT enrolment.  The following explanation we have been given might help:

>Software will see different period key formats for different customers in MTD (this will depend on where their records are held in HMRC’s systems). For the majority of customers, who will have an alpha numeric period key (e.g. 18A1), they will not have any open obligations for periods prior to joining MTD and will only be able to see fulfilled obligations for periods since they joined MTD in their software.  However customers with a full numeric period key e.g. 0419 can currently view open and fulfilled obligations for periods before they have signed up to MTD as well as those since joining MTD.  This means that, for those customers:
>
> - they can still use MTD to file returns for open obligations
> - any returns filed through MTD will be viewable through software
> - the software can also retrieve obligations fulfilled prior to the customer joining MTD, but the returns for those periods will not be viewable through software (if the customer wants to view the return they will be able to do this through their Business Tax Account).
>
>Customers will still be able to see
> - All obligations fulfilled since joining MTD through software
> - All returns filed as part of MTD through software
> - All open obligations both before and after signing up to MTD through software
> - Be able to file returns for all open obligations
> - View returns filed before joining MTD in their Business Tax Account

We have been advised that HMRC are looking at ways to improve this, and will provide more information in the future.
