### ISSUE TITLE
Fraud Header Specification Ambiguity

### ISSUE THREAD

**Issue by Roger1952** [hmrc/vat-api#601]
The fraud header docs specify the the user-agent as:

OS Family/OS Version+ (Device Manufacturer/Device Model+)

An example is given as:

Gov-Client-User-Agent: Windows/XP (/) (with a space between the XP and the (/)

In comments from HMRC via email they have rejected the header I submitted for testing and stated the format should be:

OS%20Family/OS%20Version+(Device%20Manufacturer/Device%20Model+)

So my questions are:

1. What are the "+" symbols for? They are not in the examples.
2. The example shows a space between the OS info and the device info, but the HRMC comment implies that these spaces do not exist and a + should be used.

If for example you just wanted to send Windows/11 (/) would this be sent as Windows/11%20(/) or Windows/11+(/) or Windows/11+%20(/) ?

I've been saying for some time how poor this specification really is and this is a good example.

Any comments anybody?

**Comment by GrahamHDawson** [comment]
I agree the spec is very poorly written.

The 'examples' given appear to be pre-percent encoding and really don't help a lot.
They should show both before and after percent encoding values so we know **exactly** what they mean by the specification.

**Comment by cb-rfk** [comment]
@GrahamHDawson Yes, that would have been helpful! Took us a while to work out what values needed encoding and which didn't.
Mind you, it's been over six weeks since we sent our sample headers for review and still haven't heard anything back, so perhaps it doesn't matter to HMRC anyway...

**Comment by Roger1952** [comment]
Perhaps they just are too busy fixing bugs on their end?

**Comment by GrahamHDawson** [comment]
The main issue with the SDSTeam is that they're very difficult to contact.
There's no phone number, they don't reply to emails in a timely fashion, there's no GitHub repository etc
All this means that all issues are dealt with 'in production' and they must deal with the same issues over and over again.

It really would help enormously if they had a GitHub repository where we could raise issues and search through past issues etc - and it would save them a lot of work too.

Crazy thing is we can't even get through to them to make the suggestion !

**Comment by mtd-api-team** [comment]
Please continue to raise concerns about the Fraud Prevention Headers to the SDS Team via their email address SDSTeam@hmrc.gov.uk 

Further discussion on Fraud Prevention Headers can be continued here: #565

**Comment by Roger1952** [comment]
How many times to you folks need to be told that it's a complete waste of time sending emails to SDSTeam@hmrc.gov.uk because they take months to respond! At least here there is some chance of feed back from other developers. Closing down threads doesn't make the problem go away.

**Comment by mtd-api-team** [comment]
@Roger1952 

This GitHub repository is dedicated to bugs/issues to do with the VAT-API and the code contained within this repo. 

As previously iterated in other issues, the Fraud Prevention Headers are not managed by the MTD API Team; hence as much as we wish to be useful and helpful, we can only point people in the direction of the available documentation/guidance.

Whilst we appreciate that the SDS Team may not be replying in the time frames you expect, that does not mean that raising that issue here will lead to a resolution as the SDS Team do not actively monitor this repository. 

As you mention, closing down threads does not make the problem go away. As the MTD API Team, we fully understand your frustration hence why we have issue #565 open and dedicated to this matter. To keep all the discussion focused in one place. Having said that, the GitHub Issues here are reserved for technical issues/bugs to do with the code in this repo and is not meant to serve as a Forum.

Hope that clears things up.

**Comment by Roger1952** [comment]
I very sorry, but could you please explain:

1. At what point do you regard the API to start and finish? 
   Anything that is sent and received is part of the program interface. 
   Arbitrarily splitting an IP message and disowning the first bit is bonkers. It all API.
2. Why are questions about fraud header not "technical issue"?
3. Why should ambiguities in the specification not be regarded as bugs?

Can you please also confirm if the "MTD API Team" is part of HMRC or just a random group of programmers?

**Comment by mtd-api-team** [comment]
Hi @Roger1952

To answer your questions, it is important to provide a bit of background and context to help clarify things. 

The main point of contact for developer support is in fact the **Software Developer Support Team (SDST)**. The central channel for getting support as a developer is through them, they are there to support you. They are able to liaise with the various teams that make up the APIs that you interact with. Having said that, the MTD API Team, being developers like yourself (and not a dedicated support team) understand the challenges of building software against APIs. It is because of this that we monitor the GitHub issues that are raised. We are proponents of the Agile methodology and want to ensure that we can receive feedback on the code that we have written as quickly as possible. The GitHub issues allow us to receive this feedback and improve the VAT API for you. You may have seen many instances when a bug has been submitted by a developer and the MTD API Team has fixed it and deployed the fix within hours. This type of issue is the main purpose of the GitHub Issues in this repository. 

Through your experience as a developer you will be aware that software is rarely built in isolation and is made up of various components and these components may well be built by different teams or even different organisations. Responsibility for the various components will reside with their respective teams. The VAT API is no exception.

Ultimately it all comes down to **what is the remit of this GitHub repository and its Issues section.** The MTD API Team who look after these GitHub Issues have remit over the code in [this repository](https://github.com/hmrc/vat-api/). As mentioned on a number of occasions, the MTD API Team do not manage the Fraud Prevention Headers and whilst they make up a part of the API you interact with, they are not within our remit. None of the code in this repository handles the Fraud Prevention Headers. To add to this, the questions relating to Fraud Prevention Headers may well be technical; business related or even process related, but that is beside the point as we are not positioned to answer them. SDST are the team best positioned to be able to liase with the relevant teams/organisations to find out the information you require. 

We try and be as helpful as possible and provide guidance and links where we have them. We do not have to monitor the GitHub issues but we do it because we wish to support developers like yourself. Even though the main point of contact is SDST, we do not mind developers coming directly to us to inform us of problems within our codebase. We want to be helpful and have a positive relationship with the developers our codebase impacts.

It may well be that by having this GitHub Issues channel for developers to contact us about code bugs/defects, we have in fact made it more confusing for developers. It may well be that directing all new issues to SDST and closing this channel may be the best course of action. It would lead to a more consistent response process as everything would go through SDST. By closing the GitHub issues it may also alleviate the confusion that the GitHub Issues here represent a point of contact for the entirety of Making Tax Digital, when it is solely for the code in this repository.

Thank you @Roger1952 for highlighting these issues as others may have also faced the same confusion and may not be aware of the background. It has allowed us as a team to start thinking more about how we support our codebase going forward.

All the the best

**Comment by GrahamHDawson** [comment]
@mtd-api-team 

> It may well be that by having this GitHub Issues channel for developers to contact us about code bugs/defects, we have in fact made it more confusing for developers. It may well be that directing all new issues to SDST and closing this channel may be the best course of action.

No, please do **not** do this !

What is needed is for the SDSTeam to have a similar GitHub Issues channel (or possibly channels) where **they** respond in a timely fashion to developers queries.

I'm **very** grateful for the support that the MTD API Team have been providing - it's been excellent !

Maybe what needs to happen now is for someone at a higher level to knock some heads together and get things organised - HMRC has hundreds of GitHub repositories, I'm sure they could add another 2 at least covering 'Anti-Fraud Headers' and 'oAuth Authorisation' to be monitored and responded to by the SDSTeam members.

Again **many** thanks for the MTD API Team's support - we're **not** angry or frustrated with **you**

**Comment by cb-rfk** [comment]
Fully agree with @GrahamHDawson  - everyone involved with this channel (HMRC staff and public) have been really helpful and we would not have completed our solution nearly as easily without it.

It's the "rest" of the service we all have gripes with!

**Comment by adamdavi3s** [comment]
Third'ed! Couldn't have produced our software without the help and support of the team here

**Comment by Roger1952** [comment]
So everybody is agreed.  The API folks are excellent and the SDSTeam is rubbish.

**Comment by JeeBeePee** [comment]
If the support model wasn't borked, the SDS Team answered emails, the service status page was up to date and the online helpdesk had a clue what was going on (all of which is Just Their Job), we wouldn't be on the github. If you don't want devs helping eachother out on here, I'd be quite happy to run a forum if you linked to it from here.

**Comment by Roger1952** [comment]
When you look at the total lack of joined up thinking to get this MTD VAT system working properly it is easy to seen how the the government routinely manages to overspend IT projects by humongous amounts only to end up binning them because they can't make them work. Situation normal.
