### ISSUE TITLE
View VAT Return: 404 response not consistent with other endpoints

### ISSUE THREAD

**Issue by GalonJr** [hmrc/vat-api#608]
Hello,

I have noticed that _View VAT Return_ endpoint behaves differently compared to other endpoints when it comes to 404 NOT_FOUND error scenario. While for example _Retrieve VAT liabilities_ or _Retrieve VAT payments_ accompany a 404 response with JSON body:

`{
    "code": "NOT_FOUND",
    "message": "The remote endpoint has indicated that no data can be found"
}`

_View VAT Return_ does not. It returns plain HTTP 404 response with empty HTTP body. This feels kind of inconsistent especially when the documentation lists 404 NOT_FOUND error code as one of possible responses from this endpoint.

Is this behaviour intentional?

**Comment by mtd-api-team** [comment]
Hi @GalonJr 

We are aware of this issue and a story has been raised to address this in a future release.

**Comment by KenRandall** [comment]
When do you expect to implement the coreect behaviour?

**Comment by pp07** [comment]
When i was trying to retrieve outstanding obligation for vat submission i got this same error, is this HMRC server issue?

**Comment by MrNicks** [comment]
When sending a request to the View VAT Return endpoint in the sandbox, why are we not getting back a 200 with the JSON for the submitted return?

**Comment by mtd-api-team** [comment]
Hi

We have no dates for a future release of the vat-api, but we are aware of the inconsistencies raised here and in other issue threads, and we will address them at the first opportunity to make breaking changes (in a future release).

We are unable to make any breaking changes at present in v1.0 because many vendors have finished developing against it and are using the API in production.

@MrNicks 
You should see a 200 with your VAT return, if you have previously made a successful submission and use the same periodKey to view. If you are still having problems, please confirm you have first successfully submitted the return and share your request/response details so we can investigate.

Regards
