### ISSUE TITLE
Is it possible generate Period Key in our API

### ISSUE THREAD

**Issue by Saipalazhy** [hmrc/vat-api#609]
Is it possible to generate period key in our system?

**Comment by GrahamHDawson** [comment]
The PeriodKey is returned as part of the response from the Retrieve VAT obligations endpoint

https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0#_retrieve-vat-obligations_get_accordion

ie **you** can't generate it, it must be retrieved with an obligation.
That's why the minimum your application must support is the ability to retrieve obligations and post a VAT return.

The Period Key aren't fixed but unique to the VRN being queried.

**Comment by mtd-api-team** [comment]
Hi @Saipalazhy - I hope Graham's response answers your question. If you have any further questions, please respond to this Issue.
