### ISSUE TITLE
Error 400: Bad request - in file vat return

### ISSUE THREAD

**Issue by OladotunO** [hmrc/vat-api#640]
Hi All

I get the error 400 on the json below, I haven’t figured out how to get the capitalised code to guide me so can any spot something in my json please

"{"periodKey":"18A2","vatDueSales":200,"vatDueAcquisitions":41.8,"totalVatDue":200,"vatReclaimedCurrPeriod":200,"netVatDue":158.2,"totalValueSalesExVAT":1000,"totalValuePurchasesExVAT":209,"totalValueGoodsSuppliedExVAT":0,"totalAcquisitionsExVAT":0,"finalised":true}"

**Comment by mtd-api-team** [comment]
Hi @OladotunO - I just tried the above request and got a 400 with the following body:

```
{
  "code": "INVALID_REQUEST",
  "message": "Invalid request",
  "errors": [
    {
      "code": "VAT_TOTAL_VALUE",
      "message": "totalVatDue should be equal to vatDueSales + vatDueAcquisitions",
      "path": "/totalVatDue"
    },
    {
      "code": "VAT_NET_VALUE",
      "message": "netVatDue should be the difference between the largest and the smallest values among totalVatDue and vatReclaimedCurrPeriod",
      "path": "/netVatDue"
    }
  ]
}
```

As the error body states, you have two problems:

- Your `totalVatDue` field needs to be the sum of `vatDueSales` and `vatDueAcquisitions`. In your case, that means you need to calculate it with `vatDueSales + vatDueAcquisitions` (200 + 41.8 = 241.8).
- Your `netVatDue` needs to be the difference between the largest and the smallest values among totalVatDue and vatReclaimedCurrPeriod. This basically means that you need to work out the absolute value of `totalVatDue - vatReclaimedCurrPeriod` (241.8 - 200 = 41.8).

Otherwise your data looks fine, and once you change these two fields your request should be successful.

**Comment by OladotunO** [comment]
@mtd-api-team 
Ok, many thanks, that worked.

Questions
1, However, when I tried to re file the same return I got a 403 Forbidden, reading through the documentation, I guess its because duplicate returns are rejected, ?


2, Does  The Obligations GET always return the same 2 items which match the senarios listed for VAT returns ?

3, DO I need to create new users for every filing test ? 

Cheers

Ola

**Comment by mtd-api-team** [comment]
Hi @OladotunO 

1. There are 4 scenarios in our documentation that will give a 403 error, so this could be down to multiple reasons, the error code that comes with this should give more information.

2. You will need to used the gov-test-scenarios listed in the api-documentation to get different responses from the api.

3. You can create a new user or alternatively use a different period key, which can be made up in the test environment.

Thanks.
