### ISSUE TITLE
Cannot access the API

### ISSUE THREAD

**Issue by UmicoreDundee** [hmrc/vat-api#652]
Hi All

We are having issues accessing the api service.

Whenever we open the url on the HMRC web page we are greeted with the following message:

{ "code" : "NOT_FOUND", "message" : "The requested resource could not be found." }

This is true for both the sandbox base url and the production base url.

We cannot continue to set our company up for Digital VAT if we cannot access the API-Service url.

Please help
Jonathan

**Comment by mtd-api-team** [comment]
Hi Jonathan

I've just ran some tests in the Sandbox environment and I cannot see any issues.

That 404 response is from the API Gateway, which indicates you haven't successfully hit our API. There may be some problem with your URL?

Could you respond with some more information about the request you are making in Sandbox - URL, headers, body etc - and we will investigate further. 

Regards

**Comment by UmicoreDundee** [comment]
Hi

We cannot get into neither the production nor sandbox environments, the links to do so do not work for us. 

In the longterm, we are trying to link our SAP-B1 software to allow us to report on VAT digitally. This utilises the production base url: **_https://api.service.hmrc.gov.uk_**

Found on the website: **_https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0_**

Unfortunately this was not working so I thought it would check the links directly.

When I copy the links from the website mentioned above into internet explorer, google chrome and firefox I received the error:

 { "code" : "NOT_FOUND", "message" : "The requested resource could not be found." }

Which makes me believe it is an issue with the link itself?

**Comment by mtd-api-team** [comment]
Hi Jonathan

In order to hit the VAT API you will first need to register an application on the developer hub, after which you will be able to subscribe to the service VAT (MTD) API, and then you will be able to hit the endpoints via a suitable client or application.

You will be unable to hit the endpoints through a browser because you will lack the necessary authorisation checks that happen through the API platform.

As a starting point the Sandbox URL for the Obligations API is
`https://test-api.service.hmrc.gov.uk/organisations/vat/{vrn}/obligations`

Please refer to the guidance here
https://developer.service.hmrc.gov.uk/api-documentation/docs/using-the-hub

Regards
