### ISSUE TITLE
Client or agent not authorised error

### ISSUE THREAD

**Issue by frommyuk** [hmrc/vat-api#654]
Hi Chaps,

A client of mine is getting the CLIENT_OR_AGENT_NOT_AUTHORISED error. He’s signed up to use MTD and my app works fine for other submissions.

Can you investigate the issue for me - Can I send the VAT number to you to check?

Thanks

James Kelly

**Comment by mtd-api-team** [comment]
Hi @frommyuk 

We can't investigate live issues brought to us through GitHub due to the personally identifiable nature of the data we deal with. If you email SDSTeam@hmrc.gov.uk with all pertinent information (route hit, VRN, timestamps, etc) and tell them that you've been directed to them by the team on GitHub, they will be able to send that data on to us.

**Comment by frommyuk** [comment]
Hi Chaps,

Thanks. I have emailed them this morning, but will chase them and add in your mention.

Thanks

James


  <http://www.storganise.co.uk/>

**Comment by KenRandall** [comment]
We are getting this a lot but it has always turned out to be that the Gateway ID used for authorisation is not the right one for the VRN. A better error message would be nice in these circumstances!

**Comment by mtd-api-team** [comment]
Hi @KenRandall - a decision was made by HMRC architects to wrap up most authorisation errors into one CLIENT_OR_AGENT_NOT_AUTHORISED error. This is a security measure to ensure anyone with malicious intent cannot poke our service with numerous invalid scenarios in order to gain information about the inner workings of our authorisation process. We understand that this can be frustrating, but it something which is unlikely to change.
