### ISSUE TITLE
PaymentIndicator Missing

### ISSUE THREAD

**Issue by BlueMunk** [hmrc/vat-api#655]
Hello there,

I am running Microsoft Dynamics AX 2012 and with the hotfix that Microsoft released rather close to the line.

Our software implementer is saying everything is running as it should.
We can get the obligations and then submit the return however the reponse back from the API is missing the PaymentIndicator and our system does not accept the response. We know that HMRC has our bank details and a direct debit instruction so the reponse should be either DD or BANK and not missing. The sumission is being accepted by HMRC by the fact that we have received the physical refund into our bank account for the last two months. Just our system is showing not submitted.

Is PaymentIndicator going to be correctly added in future so this problem will go away or do I need to go back to our software implementer to recode it to accept a missing response?

Thank you very much for your help in advance!

**Comment by mtd-api-team** [comment]
Hi @BlueMunk,

The Payment indicator is an optional field and we surface it through our API, when it is provided to us. As this is a live issue we recommend that you report it to [helpdesk](https://www.gov.uk/government/organisations/hm-revenue-customs/contact/online-services-helpdesk), together with relevant details so that the matter can be investigated.

Thanks,
@mtd-api-team

**Comment by BlueMunk** [comment]
Hi @mtd-api-team ,

Ok, thank you very much for the pointer - I will get in touch with helpdesk.
