### ISSUE TITLE
Internal 500 error when submitting a return

### ISSUE THREAD

**Issue by markogrady** [hmrc/vat-api#662]
FYI 

I think there may be an issue this morning I am waiting to hear from HMRC Dev support but a client tried to submit a return and received a 500 . After speaking to live services it should be fixed later today or by Monday.

**Comment by GrahamHDawson** [comment]
Hi Mark,
There was an email on Wednesday about delays after signing up that could cause error 500...

> We are aware that we are taking longer than usual to send confirmation emails to customers signing up to Making Tax Digital. 
>   
> We are contacting those affected to advise them that there is a short delay in finalising their sign up and that they should expect to receive their confirmation in the next few days if they haven’t already.  
> In the meantime there is no need for them to take any action and they should not try to sign up again or attempt to submit a return until the confirmation email has been received.  
>   
> If your customers are experiencing 500 internal server errors or 403 Agent Client not authorised error please check they have received their confirmation before advising they call the VAT Helpline. 
> 

Could it be related to that?

**Comment by nigelrainer** [comment]
We have had at least 4 cases of this in the last 24 hours.  All so far have numeric rather than alphanumeric period IDs.  Email from SDST this morning said:
"We are aware of a number of customers receiving 500 (internal server) errors when attempting to submit their VAT returns and are examining the issue urgently. Please bear with us whilst we investigate and we will contact you with an update as soon as possible. "

**Comment by nigelrainer** [comment]
We have had at least 4 cases of this in the last 24 hours. All are for registrations that have correctly signed up and for whom successful GetObligations requests have been made - so its not a 72 hour/sign-up issue.  

All so far have numeric rather than alphanumeric period IDs. 

Email from SDST this morning said:
 "We are aware of a number of customers receiving 500 (internal server) errors when attempting to submit their VAT returns and are examining the issue urgently. Please bear with us whilst we investigate and we will contact you with an update as soon as possible. "

**Comment by GrahamHDawson** [comment]
Seems like the June 'fix' may have failed then.

> The planned downtime on 17 June 2019, will include fixes for issues that some customers have been experiencing with numeric period keys.

I do wish they'd update the service interruptions page as soon as issues were reported.

**Comment by BenjiTownsend** [comment]
I'm also got customers experiencing this issue when submitting a return. It would be nice if HMRC let us know when this happened. 

The only reason I know its an issue is from this page.

**Comment by GrahamHDawson** [comment]
Update by email Friday 17:02 ...

> Internal server error 
> We are aware that today some customers have been experiencing an issue with submitting their MTD VAT returns. Customers impacted received an ‘Internal server error’ message. This issue only impacted those customers with a numeric period key. We have been working to resolve this and a fix has now been applied. We are very sorry for any inconvenience this caused

**Comment by JeeBeePee** [comment]
Also been having the same issue for numeric period keys all week.

Glad to see an email from SDST informing devs - about three days too late.

* Checks service status page * "Full service is available. Service issues - none"

* Wonders why we bothered giving feedback to HMRC on the webinar *

**Comment by KenRandall** [comment]
It would also be nice for a list of live bugs to be published somewhere with an indication of when they will be fixed!
