### ISSUE TITLE
How to add fraud prevention headers???

### ISSUE THREAD

**Issue by JOMYJAMES** [hmrc/vat-api#664]
I have read fraud prevention Docu but did not get much.still have doubts.
1. How to add fraud prevention headers in the web application of HMRC vat return?
2. How can I test it in sandbox environment?
Please help me.

**Comment by mtd-api-team** [comment]
Hi @JOMYJAMES,

  1. As HMRC API producers, unfortunately we can't give specific guidance on how to build your software as our API's are technology agnostic.  You are already adding headers to your requests (`Accept` and `Authorization`) so once you have your headers, I imagine it would be in a similar way.

  2. Unfortunately, it isn't currently possible to test the fraud prevention headers in the sandbox environment.

Kind regards,

@mtd-api-team

**Comment by JOMYJAMES** [comment]
Thank you for your kind reply

**Comment by GrahamHDawson** [comment]
Hi @JOMYJAMES ,

What are you having problems with exactly?

Is it with identifying which Anti-Fraud Headers are appropriate for your application type?
Is it with determining which application type your particular application falls under?
Is it with getting particular Anti-Fraud Header values?

If you clarify what the issue is I'm sure someone will be able to help.
May also help if you state what development language you're using.

**Comment by AndyYouens** [comment]
Not being able to test the headers in the sandbox is a right PITA!  Having to send them by email to get validated takes days/weeks to get any sort of reply.

Half the headers have nothing to do with security.  A better way of testing these headers is urgently needed if HMRC expects us to implement them.

**Comment by mtd-api-team** [comment]
Hi

Please could we invite you to use this issue https://github.com/hmrc/vat-api/issues/565 which has been left open for discussions relating to fraud prevention headers.

Thanks
