### ISSUE TITLE
The liabilities api cannot get data

### ISSUE THREAD

**Issue by yi-jun** [hmrc/vat-api#722]
the response:
{"code":"NOT_FOUND","message":"The remote endpoint has indicated that no data can be found"}

I have a problem using a formal environment
Successfully called returns and returns/{periodKey} api on 2020-02-05,
To this day, data on liabilities cannot be obtained.
What is the problem?

**Comment by mtd-api-team** [comment]
Hi @yi-jun 

If your enquiry relates to an issue with retrieving liabilities in production (rather than the Sandbox) please contact SDSTeam@hmrc.gov.uk and they will be able to look into this for you. It may be possible, however, that liabilities may not exist for the supplied vrn and period key in which case this is the intended behaviour of the endpoint.

Regards.

**Comment by yi-jun** [comment]
copy

Regards.
