### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by PrasanthNSasi** [hmrc/vat-api#725]
Hello All,

I am trying to integrate the HMRC VAT(MTD) API into our application. when I make the first request for getting the **code** and **state** from this endpoint(https://test-www.tax.service.gov.uk/oauth/authorize), I got some response like this in the POSTMAN. 

![image](https://user-images.githubusercontent.com/62351402/76993220-82ceca80-6972-11ea-8525-0858a14f73c8.png)

Please help me out with this issue.

**Comment by mtd-api-team** [comment]
Hi @PrasanthNSasi 

This part of the user setup journey is handled via a web page, which is why the page is being displayed. We access this URL inside a browser and grant authority to the vendor application from there.

https://github.com/hmrc/vat-api/wiki/Creating-Test-Users-in-the-Sandbox See step 2 

It may be possible to complete this step in Postman but I haven't personally tried it. Using a browser will enable you to click through the pages and return an oauth `code` which can be used on Step 3, back in Postman.

I would recommend doing this step in a browser.

Regards
