### ISSUE TITLE
liabilities endpoint date range

### ISSUE THREAD

**Issue by njacobs-winman** [hmrc/vat-api#774]
This is in the live environment.
If I make a request to the liabilities end point like this
organisations/vat/xxxxxxxxx/liabilities?from=2019-05-06&to=2020-05-06
on the 6th May it gives me an error 
{
    "statusCode": 400,
    "message": "DATE_RANGE_INVALID"
}
It appears that the date range has to be less than 12 months. I can't see this in the documentation. Is this the case?

**Comment by mtd-api-team** [comment]
Hi @njacobs-winman ,

Apologies for any confusion. For a retrieve liabilities request there is a maximum date range of 365 days, which is documented under the `Error scenarios` section for this endpoint. This includes leap days, which is why your request is failing. If you reduce your date range by a day, to `?from=2019-05-06&to=2020-05-05` for example, this should solve your problem.

Kind regards,
MTD-API-Team

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
