### ISSUE TITLE
X-CorrelationId

### ISSUE THREAD

**Issue by andyws** [hmrc/vat-api#8]
What is the expected usage of the X-CorrelationId on the methods in this api?

**Comment by narendravijayarao** [comment]
At the moment we are not utilising the X-correlationId for the purpose it is been implemented, but we do in future. 
It helps to identify the journey / flow of a particular user. 
In future we will be using this X-correlationId in the logging so that you can easily find out the logs for a specific user/journey based on this correlationId.

- pass it along in the HTTP header to every other service
- include it in every log message 

In logs it appears like below
[Service A][X-correlationId-1][INFO] - VAT retrieve obligation request
[Service A][X-correlationId-1][INFO] - VAT obligation connecting to DES
[Service B][X-correlationId-2][INFO] - submit VAT returns
[Service C][X-correlationId-3][INFO] - VAT obligations
[Service B][X-correlationId-2][INFO] - submit VAT returns to DES
[Service A][X-correlationId-1][INFO] - VAT obligation response
[Service B][X-correlationId-2][INFO] - submit VAT returns -Failed in retrieving the DES response

Using the X-correlationId you can easily retrieve the logs. 
Search based on "X-correlationId-2" will return

[Service B][X-correlationId-2][INFO] - submit VAT returns
[Service B][X-correlationId-2][INFO] - submit VAT returns to DES
[Service B][X-correlationId-2][INFO] - submit VAT returns -Failed in retrieving the DES response
