### ISSUE TITLE
Obligations periodKey switch

### ISSUE THREAD

**Issue by crieup** [hmrc/vat-api#807]
Hello, 
We have been notified by our compliance team that HMRC is currently migrating VAT customers to a new platform. All customers who currently have a period key which is in fully numeric format (NNNN), will see this change to alphanumeric format (NNAN/NNAA). Period keys for quarterly returns will change to a format of NNAN & monthly and annual will change to NNAA.

For this reason, HMRC strongly recommend that we do not store period keys in the software.  An obligation call should always be made immediately prior to submitting the return, to ensure that the correct period key is captured by the software.

It has also been indicated that historical period keys for submitted returns will remain the same.  The change will only apply to open periods following a client’s migration.

In our software, we are currently storing the period key when creating & preparing a VAT return for an opened period and we will probably continue to do so. We will however update our process so that the period key is updated by an obligation call when the submission to HMRC is done.

Could you please clarify one point?
Let’s say that in the case of a quarterly return the period key switch occurs on Q1 2021 (opened period). Could we have a first get.obligation returning a NNNN period key for Q1 before the migration and then a second get.obligation returning a NNAN/NNAA period key for the same opened period after the migration? 

Thanks

**Comment by adamdavi3s** [comment]
I wasn't aware of this change but would like to know the answer to this as well please

**Comment by hmrc-api-team** [comment]
Hi

Apologies for the late reply

I can only repeat the comms sent out by the Software Developers Support Team (SDST) on this because as the frontend API team, we don't have any additional information on what periodKeys to expect. 

The original email from SDST stated:

> HMRC is planning to migrate all VAT customers to a new platform over the next 12 months.  At some point during this period, all customers who currently have a period key which is in fully numeric format (NNNN), will see this change to alphanumeric format (NNAN/NNAA).
Period keys for quarterly returns will change to a format of NNAN & monthly and annual will change to NNAA.
For this reason, we strongly recommend that you do not store period keys in the software.  An obligation call should always be made immediately prior to submitting the return, to ensure that the correct period key is captured by the software.

I can only add, where the wrong period key were applied, backend services would reject it and you would need to re-submit using the new period key.

Regards

**Comment by hmrc-api-team** [comment]
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.
