### ISSUE TITLE
Invalid Refresh Token

### ISSUE THREAD

**Issue by ShoLongBruce** [hmrc/vat-api#833]
A user has needed to re-authorise as their authorisation code has expired. They have managed to grant authority and managed to get the access tokens.

However when they try to getObligations, they're getting the InvalidRefeshToken error. Normally if this happens, we just go through the authorrisation process again and works a second time.

We have tried re-authorising several times and got the access tokens, but still coming up with invalidrefresh token each time we try to get obligations.
This is on the live site.
Can someone suggest what we can try next?

Thanks

**Comment by hmrc-api-team** [comment]
Hi @ShoLongBruce 

We are not aware of any issues, and everything is working on our side. Is it possible that the user has supplied a different VRN to the credentials they used to authorise the vendor application. Or in other words, they may be authorising the wrong VRN?

Because we cannot see what is happening within the auth service, if this problem persists please contact the Software Developers Support Team on SDSTeam@hmrc.gov.uk, who will be able to contact the relevant teams.

Regards, MTD API team

**Comment by ShoLongBruce** [comment]
I have checked and double checked the VRN, and credentials. I have now contacted the SDS team

**Comment by MrSent** [comment]
I'd remove all tokens from wherever you store them, and try re-granting of authority. Basically starting afresh as if the customer has never used the system. As for contacting SDS Team, my experiences so far have been that it's largely a waste of time.

I had recent issues with authenticating where it seems that my MTD module was defaulting to TLS v1.0 as it was built against .NET 4.5. Overriding that, and forcing a higher TLS version allowed the re-granting of authority to occur without issue.

**Comment by cb-rfk** [comment]
Hi @MrSent 

Can you elaborate a bit further on the TLS issue you had? We've been having problems with new user sign-ups since mid Dec whereby they get redirected to HMRC, log into the Gateway and attempt to complete the App authorisation step, but then get a Not Authorised error when returning to our application.  Is this similar to what you saw?

Cheers.

**Comment by ShoLongBruce** [comment]
> 
> 
> I'd remove all tokens from wherever you store them, and try re-granting of authority. Basically starting afresh as if the customer has never used the system. As for contacting SDS Team, my experiences so far have been that it's largely a waste of time.
> 
> I had recent issues with authenticating where it seems that my MTD module was defaulting to TLS v1.0 as it was built against .NET 4.5. Overriding that, and forcing a higher TLS version allowed the re-granting of authority to occur without issue.

Thanks for that. Yes we always clear down everything when re-authhorising that way we're sure everything is up to date. Suprislingly SDS Team has come back to me. They're saying my error is not a refresh token error and I'm actually getting a 403 error which implies that the  wrong User ID & Password details have been used for the authorisation process. I have left them to investigate with HMRC and will try again once they confirm the correct credentials.

**Comment by MrSent** [comment]
> Hi @MrSent
> 
> Can you elaborate a bit further on the TLS issue you had? We've been having problems with new user sign-ups since mid Dec whereby they get redirected to HMRC, log into the Gateway and attempt to complete the App authorisation step, but then get a Not Authorised error when returning to our application. Is this similar to what you saw?
> 
> Cheers.

Sure. My module was written in C# and built against .NET 4.5. It seems that .NET 4.5 will default to TLS v1.0. I didn't want to change the .NET version because that causes me other problems elsewhere.

The errors I kept getting were when the customer was trying to do anything like get obligations or authenticate and I would get an authorisation error OR if the customer was new to our module, I would get a message saying the refresh token cannot be blank. Basically all the errors seemed to be red herrings.

In the app.config file I added this into the runtime section

```xml
<configuration>
  <runtime>
    <AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false"/>
  </runtime>
</configuration>
```
This forces a higher version of TLS to be used.

**Comment by cb-rfk** [comment]
@MrSent 

Thanks for that. 

Doesn't sound the same problem that we've got as pre-existing users are unaffected, it's just the first application authorisation for new users we are stuck with.

Will get some users to try again and then email SDST with details...

**Comment by MrSent** [comment]
> @MrSent
> 
> Thanks for that.
> 
> Doesn't sound the same problem that we've got as pre-existing users are unaffected, it's just the first application authorisation for new users we are stuck with.
> 
> Will get some users to try again and then email SDST with details...

There are a couple of things you could look at with new users. The HMRC gateway account of the user that is trying to authenticate must be enabled for MTD. Whoever is the administrator of the gateway account for the customer can log in and see all users at that company and they must enable specific users to allow them to use MTD. Or you must authenticate by logging in with the gateway account administrator.

I've had this where a customer has created an HMRC gateway account and they can do things without issue. Another employee there creates their own gateway account within the organisation and they can't do MTD because the initial account which is the administrator needs to enable them to use MTD. The trouble is as a developer I don't know how to guide my end customers because I have no reference material showing how to set their account up properly.

With the astronomical documentation provided by HMRC, there is so much of it which is of little use and no screenshots, and things you do need don't appear to be there. It's all well and good when things are available but if you don't know what search terms to use, you can't search for them.

**Comment by cb-rfk** [comment]
It is so frustrating when things work for one customer and not for another and we have no way of debugging the process! 😂

But what you've added makes total sense and definitely something we can follow up on with the users, so thanks again.

**Comment by ShoLongBruce** [comment]
User managed to get new gateway id and pwd. All working now. Thanks

**Comment by MrSent** [comment]
Glad to have been some help.
