### ISSUE TITLE
Error 500 on authorisation today 

### ISSUE THREAD

**Issue by sonicmule** [hmrc/vat-api#84]
Anyone else getting Error 500 when trying to obtain an access token from /oauth/token ?
Hoping to prepare for the hackathon in Birmingham tomorrow.

**Comment by jacobbrownlow** [comment]
Hi @sonicmule

We are aware of this reoccurring issue (https://github.com/hmrc/vat-api/issues/82) and I have contacted the API Platform Support team for a response.

To re-iterate, this problem is outside of our control as it relates to the wider HMRC API Plaform and is not exclusive to the MTD Self Assessment and VAT APIs.

If you'd like to send this issue to this email address SDSTeam@hmrc.gsi.gov.uk again, that may prompt them to fix it faster. Thanks

Sorry for the inconvenience.
Jacob

**Comment by sonicmule** [comment]
Thanks for the reply, I have contacted the SDSTeam already.
Just making sure it isn't me!

**Comment by RichardBainesHMRC** [comment]
It's related to some new functionality we've released to support changes to authentication, it looks like it's still giving unexpected behaviour that's preventing token creation. We've rolled back @sonicmule, please can you retry?

**Comment by sonicmule** [comment]
It's working now thanks.
Is this update going to be held until after tomorrow, might be a bit of a problem for us at the Hackathon if we can't get in.
