### ISSUE TITLE
The 'organisations/vat' API is currently unavailable 

### ISSUE THREAD

**Issue by alanfinnharris** [hmrc/vat-api#844]
Hi SDSTeam.
We are experiencing the [503] Service Unavailable error today, 'The 'organisations/vat' API is currently unavailable', can you please tell us if there is a problem with the service today.
Many Thanks,
Alan

**Comment by wadewomersley** [comment]
2nd'd

**Comment by cb-rfk** [comment]
We had an alert via statuspage.io this morning:

VAT MTD Service Unavailable

Incident status: Identified 

The issue has been identified and a fix is being implemented. 

Time posted

Mar 16, 09:58 UTC 

Components affected

 
Production environment


Probably worth signing yourself up for the alerts too :)
 
--

**Comment by alanfinnharris** [comment]
Cheers, thank you

**Comment by osrec** [comment]
Is someone from the HMRC team aware of this? We have a number of users complaining of issues and the following status page provides no info: https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues - makes it look like our software is at fault!

**Comment by alanfinnharris** [comment]
For what it's worth it is mentioned here;
https://api-platform-status.production.tax.service.gov.uk/

**Comment by osrec** [comment]
> For what it's worth it is mentioned here;
> https://api-platform-status.production.tax.service.gov.uk/

Thanks for this! They should probably link to this page on https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues

**Comment by cb-rfk** [comment]
Update from HMRC...

VAT MTD Service Unavailable
An update has been posted
We previously advised you that we would be undertaking scheduled maintenance to HMRC’s digital services in order to deliver a number of iterative enhancements to the functionality of the Making Tax Digital (MTD) for VAT service.

Unfortunately, following successful delivery of this functionality over the weekend, an issue has been identified which is impacting the ability of some MTD for VAT customers to submit a return.

In order to enable a fix to be delivered, the ‘Return Submission’ element of MTD for VAT requires shuttering. As a result, it is currently not possible for customers or agents to submit a VAT return through the MTD service.

All other elements of the VAT service (such as sign-up and payment) remain open. There is no interruption to applications for the VAT deferral New Payment Scheme. The MTD for ITSA service is unaffected.

We are working to resolve this issue as soon as possible and expect the full service to return on the morning of Thursday 18th March. If this situation changes, we will notify you immediately.

We apologise for any inconvenience this may cause
Time posted
Mar 16, 16:34 UTC

**Comment by JeeBeePee** [comment]
> Is someone from the HMRC team aware of this? We have a number of users complaining of issues and the following status page provides no info: https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues - makes it look like our software is at fault!

They never, ever update that page. I've asked them (SDS Team) to sort it out every time they have an outage, which is pretty much after every change they roll out. I always get a reply saying it's some other team's fault. They either don't appreciate how important it is to keep it updated, or they don't care.

**Comment by JeeBeePee** [comment]
> In order to enable a fix to be delivered, the ‘Return Submission’ element of MTD for VAT requires shuttering. As a result, it is currently not possible for customers or agents to submit a VAT return through the MTD service.
> 
> All other elements of the VAT service (such as sign-up and payment) remain open.

This is such horsesh*t. It's not just return submission that's borked, it's the whole service.

**Comment by JeeBeePee** [comment]
Frankly, I'm tired of politely asking HMRC to sort out fundamental issues in the way they deliver the MTD services. Time to call them out for what they are. Rank amateurs.

**Comment by hmrc-api-team** [comment]
Hi all,

In the interest of keeping discussion on topic I would like to remind you that this Issues page is for questions and issues pertaining to code within the vat-api repository. The team who maintain this code **are not the SDSTeam**; SDSTeam do not monitor this repository and therefore there is only so much help that we can give you. Questions about live support should be directed at SDSTeam, not here.

That being said, we have had to shutter the VAT API. An issue downstream to us was identified with submitting a VAT return, where the return was successful but an error was still being thrown. The team who identified this problem are aware and are working on a solution.

As the API Platform that we sit on is currently built we cannot only shutter per-endpoint, it's kind of all-or-nothing for us. If you weren't made aware of this then I'll chase up why a notice wasn't sent out - as far as we were aware, this shuttering was communicated to our third-party vendors. I'll also chase up why that availability page wasn't updated, since it should have been updated yesterday morning.

Also I'd like to note that swearing on this Issues page will not be tolerated. I have edited out the swearword from a comment in this thread; please don't do that again.

**Comment by JeeBeePee** [comment]
We know this isn't for live issues. We're here because the support process is not fit for purpose and the comms to software providers and end users (via the service status page) are so bad. Sorry if a starred out mild swear upsets you, but you (you, HMRC, I don't care about your internal team structure) are not listening to polite requests for obvious and easily implemented changes.

We have been promised improvements for two years now. If anything, it's worse than ever.

Do feel free to feed the above back to whoever is responsible for the overall MTD service, and also please impress upon them my continued surprise that they manage to remain in the job.

**Comment by hmrc-api-team** [comment]
@JeeBeePee 

As you are aware, this is not the place to raise grievances about the live process; we have nothing to do with that process. 

I will keep this thread open so other vendors know about vat-api being shuttered. However, please keep any further discussion related to the code in the vat-api or the thread will be locked.

**Comment by hmrc-api-team** [comment]
Hi all, the vat-api is now unshuttered. Requests to vat-api should be going through successfully now so I'm closing this thread - please comment back if you still see 503 errors.

Regards
