### ISSUE TITLE
Undocumented error received on API request

### ISSUE THREAD

**Issue by nigelrainer** [hmrc/vat-api#867]
Re-raising this issue as HMRC unilaterally closed item #658 without a satisfactory resolution.

We have had a number of further occurrences of getting back an HTML error rather than a JSON message with the content "Oops, an error occurred". This is an example:
<title>Error</title> <style> html, body, pre { margin: 0; padding: 0; font-family: Monaco, 'Lucida Console', monospace; background: #ECECEC; } h1 { margin: 0; background: #A31012; padding: 20px 45px; color: #fff; text-shadow: 1px 1px 1px rgba(0,0,0,.3); border-bottom: 1px solid #690000; font-size: 28px; } p#detail { margin: 0; padding: 15px 45px; background: #F5A0A0; border-top: 4px solid #D36D6D; color: #730000; text-shadow: 1px 1px 1px rgba(255,255,255,.3); font-size: 14px; border-bottom: 1px solid #BA7A7A; } </style>
Oops, an error occurred

    <p id="detail">
        This exception has been logged with id <strong>7ihhi4hab</strong>.
    </p>

</body>

This is on a submission and is then immediately followed by an invalid_grant and an expired token.

We have raised this with SDST a number of times and just get back "Apologies for the delay in response. There was an issue on the morning of the XXth January which meant that the service had to be shuttered for a short period of time. Thanks for raising this & apologies for the inconvenience."

I have asked them to explain:

    What at their end is causing this?
    When the documentation will be updated to reflect that this type of error is possible?
    When this unhandled API error is to be fixed?

**Comment by hmrc-api-team** [comment]
Hi @nigelrainer,

The issue was closed because, as mentioned [previously](https://github.com/hmrc/vat-api/issues/658#issuecomment-509581475), problems with authorisation are not within this team's control. This repository's issues are reserved for technical queries relating to the VAT-API only. With regards to documentation, our API documentation only includes errors which the VAT API service itself may return as we do not have visibility, or control over, the responses you may receive from other services on the platform such as authorisation. Only SDST are capable of answering these queries and they do not monitor these issue pages.

Kind regards,
MTD API Team

**Comment by nigelrainer** [comment]
And SDST keep saying “A partner team is looking further into this”.  All I want is someone to acknowledge the issue, own it and tell me what is going on.  Basic “customer” service.
