### ISSUE TITLE
Sandbox: Submission 500 response when using organisation test user on Create test user service

### ISSUE THREAD

**Issue by charles-f** [hmrc/vat-api#873]
# Bug report

You must read the information below before you submit a bug report. 

The MTD API team cannot help if your bug report is about:

- Fraud Prevention Headers
- Issues relating to OAuth2
- Subscribing or registering to use the API Platform, MTD enrolment, de-enrolment, registration for VAT, Beta services, etc.
- Issues integrating with the API Platform (e.g. setting up an application/access)
- Code examples in a given programming language
- Business-related questions or processes pre MTD
- Scheduled maintenance windows and days
- Onboarding (e.g. registering, obtaining keys)
- Performance metrics

For any of the above, you **must** contact the Software Developer Support Team directly at SDSTeam@hmrc.gov.uk.  The SDS Team do not monitor this repository.

This repository is for bug reports relating to VAT API code in this repository only.

Fill in the sections below to submit your bug report:

- [ ] Documentation
- [x] API 

**Describe the bug**

I am creating an organisation test user here - https://developer.service.hmrc.gov.uk/api-test-user - then authorising/granting access, then exchanging the authcode for the access tokens - which I then use to get the obligations (which works) but when trying to submit I get a 500 response error.

Note this doesn't happen when you select individual test users on above link.

These requests that I'm doing here are all done in Postman to remove my product from the equation (of what could be going wrong).

Note that in my automated tests, I still generate test users with my applications server token, which is not the same way as this link is generating test users - and by creating the test user data via this method (organisation) - then the submission still works.

This is something that has only just started happening - so I think it's a change on HMRC side (as I'm using postman to run these tests so it is not my product at all).

**To Reproduce**
* go to https://developer.service.hmrc.gov.uk/api-test-user
* select organisation
* grant access and get the authcode
* hit the POST https://test-api.service.hmrc.gov.uk/oauth/token endpoint with your applications client_id/secret/auth_code
** this returns access/refresh tokens in the response
* take the access token and the VRN from the first step and then hit the GET obligations endpoint to verify you have granted/authorised
* try to submit

**Expected behavior**
* Submission works - the same as individual test user data

**Screenshots / Requests / Responses**
![image](https://user-images.githubusercontent.com/45665592/135647729-7c19c23c-5bc6-4e1f-846e-da19ddbf5292.png)

**Additional context**

It works when I create the test user for organisation through authorising the request with the applications server token
![image](https://user-images.githubusercontent.com/45665592/135647965-97ac20fe-a7f6-44d5-957b-ccd7dd9d11f0.png)

But when creating an organisation through https://developer.service.hmrc.gov.uk/api-test-user then the submission doesn't work and returns 500 internal server error

**Comment by hmrc-api-team** [comment]
Hi @charles-f,

We are currently investigating an issue in the test environment which is causing VAT return submissions to fail with a 500 response for certain users. We will keep you updated here as we try to determine the cause and start working towards a solution. Apologies for the disruption.

Kind regards,
MTD API Team

**Comment by charles-f** [comment]
Hi @hmrc-api-team,

Do you have any update on the investigation of this please?

Kind regards,
@charles-f

**Comment by dhanajik** [comment]
@hmrc-api-team,

I am also facing the same issue. My code was absolutely tested on the test environment previously but since a couple of days getting below error while submitting returns 

500 Internal Server Error: [{"code":"INTERNAL_SERVER_ERROR","message":"An internal server error occurred"}]

Please have a look into this on priority.

Thank you

**Comment by hmrc-api-team** [comment]
Hi all, we have been informed that a fix has now been put in place. New Organisations that are generated should have the relevant user information, so the fact that Organisation users through the frontend are also generated with "mtd-income-tax" shouldn't be a problem anymore.

Since the fix was put into place for new Organisations, please regenerate an Organisation user for yourself to get a working user through the frontend.

If after creating a new Organisation user you are still experiencing this problem please comment back on this Issue and we can raise it with the relevant team.

Kind regards
