### ISSUE TITLE
503 - Scheduled Maintenance and Service unavailable message

### ISSUE THREAD

**Issue by tim-xero** [hmrc/vat-api#90]
Hi There
Regarding the 503 error
Will HMRC provide advanced notification around scheduled maintenance plans and anticipated down times? Who will they provide it to? 
Or will HMRC only provide the return message of scheduled maintenance as a result of someone trying to use the service/api's? 
If so, whats the practical difference between scheduled maintenance and service unavailable messages?  because no one would know the difference in real life terms.

**Comment by jacobbrownlow** [comment]
Hi @tim-xero 

Apologies that this issue was overlooked.

We are not aware of any planned scheduled maintenance. Our team certainly isn't planning on any.

If you are still concerned about this topic I would advise you to speak to the Software Developers Support Team by emailing SDSTeam@hmrc.gsi.gov.uk 

Regards, Jacob
